### ISSUE TITLE
Pronouns are currently case sensitive

### ISSUE THREAD

**Issue by 00p513-dev** [GeopJr/PronounBird#4]
This doesn't work in cases like Luana's profile, where she has capitalized the first letter of her pronouns

https://twitter.com/1u4n4MH

**Comment by GeopJr** [comment]
Works for me. Could you try refreshing the page? For some reason it stops working eg. when switching accounts (mostly on firefox), I'll look into it more in the following days.

(BTW, bios get lowercased so it's not a case sensitivity problem https://github.com/GeopJr/PronounBird/blob/main/src/modules/pronounHandler.js#L155)

![example](https://user-images.githubusercontent.com/18014039/129731125-fa9ff190-2f21-4191-afbc-018dd50f369b.png)

**Comment by 00p513-dev** [comment]
Hmm it works sometimes, but sometimes it doesnt. Anything I can do to help?

**Comment by GeopJr** [comment]
I need to write docs, but for now here's a small guide on the internals:

## Building & Loading

(I used pnpm, npm should also work though)
- `pnpm install`
- `pnpm run start` (or `start:ff` for firefox (https://github.com/GeopJr/PronounBird/blob/main/package.json#L11-L18))
- extension-cli will watch for changes. You can now load the extension unpacked in your browser of choice by selecting the `dist/` (or `dist-ff/`) folder. (The option to load unpacked should be somewhere in the extensions/addons page of your browser)

> Note: You will probably need to refresh the extension/addon in the debug page manually after every change

## Internals

Everything has comments either from me or upstream (doucheblock). What I do differently is get rid of the queue system and instead save pronouns in storage (because unlike doucheblock, I need to access them all the time without spamming the twitter api). Most `src/modules` are self-explanatory + I didn't change much other than remove unused functions. `pronounHandler.js` contains functions that handle detecting links, getting bios, parsing pronouns, adding them to DOM etc.

### How it works

The functions in `pronounHandler` are being consumed by the content script (`src/content.js`). Initially it requests the tokens and then calls the observer (I suspect that here's the main problem caused by tokens not being available in time or at all, but needs testing). The observer (aka [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/MutationObserver)) goes through all now-added Nodes, gets their links, filters through them to get only those that havent had their DOM modified yet by pronounbird + are handle links + are not in storage, and then calls `PronounHandler#requestBios` passing only the totally new users.

Eventually `PronounHandler#executeBlock` gets called (either from `PronounHandler#requestBios` or forcefully after the new user handler), which requests the storage, goes through all of them and modifies the DOM accordingly.

Lastly, there's a setInterval in content script that clears the Storage every 5 mins if it's above 5k entries to avoid using too much (since while browsing twitter you might come across several people with multiple pronouns). However Storage does also get cleared when the observer first runs.

For the current issue my suspicions are:
- tokens not being available (as mentioned above)
- `PronounHandler#executeBlock` uses [`StorageArea#get`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/get) which during development didn't always play nice
- the setInterval could remove entries just before they are needed by `PronounHandler#executeBlock` but that doesn't seem to be the case at least right now since the issue occurs even though Storage is almost empty.
- Twitter API errored

Potential fixes:
- retry until tokens are ready (probably also stop after a minute or 10 tries or something)
- no idea what to do if it's a `StorageArea#get` issue other than try alternatives
- If it's a Twitter API error, should probably retry some more times
- Reinitialize the observer on page mount & get the new tokens on account switch (this is probably the problem on Firefox, that somehow doesn't affect chromium (at least from my tests))

Some of the above potential fixes have been added to my todo list.
Any testing done to narrow down the issue would be more than enough :)

**Comment by GeopJr** [comment]
I'm 99% sure the issue is now fixed. The problem was that headers don't always have the correct csrf token so instead now I'll take it from cookies with headers as a fallback.
